version: "3.0"
services:
  SingleNode:
    restart: always
    image: redis:6.2.0
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false
    command: redis-server --notify-keyspace-events KEA
